name: UserServiceTests

on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_user_service_tests:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: read
      
    env:
      project_dir: ./UserService 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          source-url : https://nuget.pkg.github.com/oldboni22/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore
        run: dotnet restore ${{env.project_dir}}

      - name: Build 
        run: dotnet build ${{ env.project_dir }} --no-restore

      - name: RunTests
        run: dotnet test ${{ env.project_dir }} --no-build
        env:
          GRpc__UserApiPort: "5100"
          GRpc__TopicApiPort: "5200"
          GRpc__UserApiAddress: "https://localhost:5100"
          GRpc__TopicApiAddress: "https://localhost:5200"
          
          Minio__Endpoint: "localhost:9000"
          Minio__AccessKey: "aboltus"
          Minio__SecretKey: "loshara"

          SerilogSettings__LogFile: "log.txt"
          ApplicationPort: "7082"
    
